name: Deploy Windows Forms Application

on:
  workflow_call:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: List Available Artifacts
    #   run: |
    #     echo "Listing available artifacts..."
    #     curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
    #       https://api.github.com/repos/${{ github.repository }}/actions/artifacts

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    # - name: List Downloaded Files
    #   run: |
    #     echo "Listing downloaded files..."
    #     dir /s
    #   shell: cmd

    - name: Upload to Azure Storage
      run: |
        echo "Zipping files before uploading to Azure Storage..."
        Compress-Archive -Path .\* -DestinationPath ./artifacts/app.zip
        echo "Uploading zipped file to Azure Storage..."
        az storage blob upload \
          --account-name projetodotnet \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
          --container-name windowsformapp \
          --file ./artifacts/app.zip \
          --name ${{ github.event.repository.name }}.zip
      env:
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

