name: Deploy Windows Forms Application

on:
  workflow_call:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: List Downloaded Files
      run: |
        echo "Listing downloaded files..."
        dir /s
      shell: cmd

    - name: Create ZIP from Downloaded Artifacts
      run: |
        echo "Creating ZIP file from downloaded artifacts..."
        # Cria diretórios temporários
        $source = "temp"
        $output = "artifacts"
        if (-not (Test-Path -Path $output)) {
          New-Item -ItemType Directory -Path $output | Out-Null
        }
        if (-not (Test-Path -Path $source)) {
          New-Item -ItemType Directory -Path $source | Out-Null
        }
        # Copia os arquivos (exceto artifacts) para a pasta temporária
        Get-ChildItem -Path . -Exclude $output, $source | ForEach-Object {
          Copy-Item -Path $_.FullName -Destination $source -Recurse
        }
        # Remove o zip anterior, se existir
        $zipPath = Join-Path $output "build-artifacts.zip"
        Remove-Item -Path $zipPath -Force -ErrorAction SilentlyContinue
        # Cria o novo zip a partir da pasta temporária
        Compress-Archive -Path "$source\*" -DestinationPath $zipPath
        # Limpa a pasta temporária
        Remove-Item -Path $source -Recurse -Force
      shell: pwsh

    - name: Debug - Verificar ZIP dos Artefatos
      run: |
        echo "Verificando se o arquivo ZIP foi criado..."
        if (Test-Path -Path ./artifacts/build-artifacts.zip) {
          Write-Host "Arquivo ZIP encontrado:"
          Get-Item ./artifacts/build-artifacts.zip | Format-List
          Write-Host "Conteúdo do ZIP:"
          Expand-Archive -Path ./artifacts/build-artifacts.zip -DestinationPath ./artifacts/zip-contents -Force
          Get-ChildItem -Path ./artifacts/zip-contents -Recurse
        } else {
          Write-Error "Arquivo ZIP não encontrado!"
          exit 1
        }
      shell: pwsh

    - name: Upload to Azure Storage
      run: |
        echo "Uploading zipped file to Azure Storage..."
        az storage blob upload `
          --account-name projetodotnet `
          --account-key ${{ secrets.AZURE_STORAGE_KEY }} `
          --container-name windowsformapp `
          --file ./artifacts/build-artifacts.zip `
          --name ${{ github.event.repository.name }}.zip
          --overwrite
      env:
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

    - name: List Blobs in Container
      run: |
        az storage blob list --account-name projetodotnet --account-key ${{ secrets.AZURE_STORAGE_KEY }} --container-name windowsformapp

