name: Deploy to Docker

on:
  workflow_call:

permissions:
    contents: read
    packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
       distribution: 'temurin'
       java-version: '17'
            
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output

    - name: Allow gradlew execution
      run: chmod +x ./gradlew

    - name: Move JAR to root as app.jar
      run: |
        find . -name "*.jar" -exec cp {} app.jar \;


    - name: Generate Dockerfile
      run: |
        cat <<EOF > Dockerfile
        FROM eclipse-temurin:17-jdk-alpine
        COPY app.jar app.jar
        ENTRYPOINT ["java", "-jar", "app.jar"]
        EOF

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker image
      run: |
        IMAGE_NAME=ghcr.io/$(echo "${{ github.repository_owner }}/${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]'):latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_STORAGE_KEY }} 

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
