name: Deploy Java Gradle Library

on:
  workflow_call:
       
jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: build-output

            - name: Publish to GitHub Packages
              run: ./gradlew publish
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}