name: Reusable CI Pipeline

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      configuration:
        required: false
        type: string
        default: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration ${{ inputs.configuration }}

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish API binaries
        run: dotnet publish --no-build --configuration ${{ inputs.configuration }} --output ./publish

      - name: Upload API binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-binaries
          path: ./publish
